name: Job - iOS - Assemble Prod IPA

on:
  workflow_call:
    inputs:
      version_name: { required: true, type: string }
      version_code: { required: true, type: string }
    outputs:
      artifact-name:
        value: ${{ jobs.build.outputs.artifact-name }}

jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 40
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/iosApp/Gemfile
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Xcode setup
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Setup ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: iosApp/Podfile.lock

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/*.toml*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Environment variables
        env:
          GOOGLE_SERVICES_JSON_PRODUCTION: ${{ secrets.GOOGLE_SERVICES_JSON_PRODUCTION }}
          GOOGLE_SERVICES_PLIST_PRODUCTION: ${{ secrets.GOOGLE_SERVICES_PLIST_PRODUCTION }}
        run: |
          mkdir -p composeApp/src/sandbox
          mkdir -p composeApp/src/production
          mkdir -p iosApp/iosApp/Firebase
          echo GOOGLE_SERVICES_JSON_PRODUCTION | base64 --decode >> composeApp/src/production/google-services.json
          echo $GOOGLE_SERVICES_PLIST_PRODUCTION | base64 --decode >> iosApp/iosApp/Firebase/GoogleService-production.plist

      - name: Build and Deploy to TestFlight
        env:
          ASC_KEY_ID: ${{ secrets.IOS_APPSTORE_CONNECT_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.IOS_APPSTORE_CONNECT_ISSUER_ID }}
          ASC_KEY_P8: ${{ secrets.IOS_APPSTORE_CONNECT_API_KEY }}
          ASC_TEAM_ID: ${{ secrets.IOS_TEAM_ID }}
          VERSION_NAME: ${{ inputs.version_name }}
          VERSION_CODE: ${{ inputs.version_code }}
        run: |
          cd ./ios
          bundle exec fastlane beta