name: Job - Unit Tests

on:
  workflow_call:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Java 17
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Caching gradle
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/*.toml*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Environment
      - name: Environment variables
        env:
          GOOGLE_SERVICES_JSON_SANDBOX: ${{ secrets.GOOGLE_SERVICES_JSON_SANDBOX }}
          GOOGLE_SERVICES_PLIST_SANDBOX: ${{ secrets.GOOGLE_SERVICES_PLIST_SANDBOX }}
        run: |
          mkdir -p composeApp/src/sandbox
          mkdir -p composeApp/src/production
          mkdir -p iosApp/iosApp/Firebase
          echo $GOOGLE_SERVICES_JSON_SANDBOX | base64 --decode >> composeApp/src/sandbox/google-services.json
          echo $GOOGLE_SERVICES_PLIST_SANDBOX | base64 --decode >> iosApp/iosApp/Firebase/GoogleService-sandbox.plist

      # Running unit tests
      - name: Unit tests
        run: ./gradlew testDebugUnitTest testSandboxDebugUnitTest

      # Publish test report
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'