name: Pull Request
'on':
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.png'
jobs:
  unit-tests:
    uses: ./.github/workflows/job-unit-tests.yml
    secrets: inherit