name: Pull Request
'on':
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.png'
jobs:
  unit-tests:
    uses: ./.github/workflows/job-unit-tests.yml
    secrets: inherit

  assemble:
    uses: ./.github/workflows/job-android-assemble-sand.yml
    secrets: inherit
    with:
      version_name: 1.0.0
      version_code: 1