name: Pull Request
'on':
  pull_request:
    branches:
      - main
    paths:
      - '**/*.gradle'
      - '**/*.toml'
      - '**/*.kt'
      - '**/*.kts'
      - '**/*.xml'
      - '**/pull-request.yml'
jobs:
  unit-tests:
    uses: ./.github/workflows/job-unit-tests.yml
    secrets: inherit

  dependency-diff:
    uses: ./.github/workflows/job-dependency-diff.yml
    secrets: inherit

  ui-tests:
    uses: ./.github/workflows/job-android-uitest.yml
    secrets: inherit

  deploy-wasmjs:
    uses: ./.github/workflows/job-wasmjs-deploy.yml
    secrets: inherit